SET search_path = tsup;
INSERT INTO EMPLOYEE(ID, NUMBER, LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, USERNAME) 
	VALUES (1, 'A10210', 'LORENZO', 'LOYCE', 'l.lorenzo', 'l.lorenzo@gujitsu.ph');
INSERT INTO EMPLOYEE(ID, NUMBER, LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, USERNAME) 
	VALUES (2, 'A10456', 'DE LEON', 'JC', 'jc.deleon', 'jc.deleon@gujitsu.ph');
INSERT INTO EMPLOYEE(ID, NUMBER, LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, USERNAME) 
	VALUES (3, 'A15893', 'MACABUDBUD', 'JAY IAN', 'j.macabudbud', 'j.macabudbud@gujitsu.ph');

--Access Type
INSERT INTO EMPLOYEE_AUTH(ID, AUTH_NAME, USERNAME) VALUES (1, 'PMO', 'l.lorenzo');
INSERT INTO EMPLOYEE_AUTH(ID, AUTH_NAME, USERNAME) VALUES (2, 'INSTRUCTOR', 'jc.deleon');
INSERT INTO EMPLOYEE_AUTH(ID, AUTH_NAME, USERNAME) VALUES (3, 'PMO', 'j.macabudbud');


